# GitHub Labels Configuration
# This file defines the labels used for issues and pull requests

labels:
  # Type labels
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"
  - name: "question"
    color: "d876e3"
    description: "Further information is requested"
  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"
  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  # Priority labels
  - name: "high priority"
    color: "ff0000"
    description: "High priority issue"
  - name: "medium priority"
    color: "ffa500"
    description: "Medium priority issue"
  - name: "low priority"
    color: "ffff00"
    description: "Low priority issue"

  # Status labels
  - name: "needs-triage"
    color: "ffa500"
    description: "Issue needs to be reviewed and categorized"
  - name: "in progress"
    color: "1d76db"
    description: "Work in progress"
  - name: "blocked"
    color: "ff0000"
    description: "Blocked by another issue or dependency"
  - name: "ready for review"
    color: "00ff00"
    description: "Ready for code review"
  - name: "approved"
    color: "00ff00"
    description: "Approved for merge"

  # Component labels
  - name: "ui"
    color: "e4e669"
    description: "User interface related"
  - name: "backend"
    color: "d93f0b"
    description: "Backend logic related"
  - name: "fuzzy-logic"
    color: "fbca04"
    description: "Fuzzy logic functionality"
  - name: "i18n"
    color: "c2e0c6"
    description: "Internationalization"
  - name: "testing"
    color: "fef2c0"
    description: "Testing related"
  - name: "performance"
    color: "ffa500"
    description: "Performance related"

  # Dependency labels
  - name: "dependencies"
    color: "0366d6"
    description: "Pull requests that update a dependency file"
  - name: "python"
    color: "3776ab"
    description: "Python related changes"
  - name: "github-actions"
    color: "2088ff"
    description: "GitHub Actions related"
  - name: "pre-commit"
    color: "ff6b6b"
    description: "Pre-commit hooks related"

  # Special labels
  - name: "breaking change"
    color: "ff0000"
    description: "Breaking change"
  - name: "security"
    color: "ff0000"
    description: "Security related"
  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"
  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
  - name: "invalid"
    color: "e4e669"
    description: "Something is wrong" 