name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'

template: |
  ## What's Changed
  $CHANGES

  {% if $NEW_CONTRIBUTORS %}
  ## New Contributors
  $NEW_CONTRIBUTORS
  {% endif %}

  ## Contributors
  $CONTRIBUTORS 