[tool.black]
line-length = 88
skip-string-normalization = false
skip-magic-trailing-comma = false
preview = true
exclude = '''
/(\.|venv|env|build|dist|__pycache__)/
''' 

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = [".venv", "venv", "build", "dist", "__pycache__"] 