name: Quality Checks

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pre-commit (all files)
        run: |
          . .venv/bin/activate
          pre-commit run --all-files
      - name: Run type checks (mypy)
        run: |
          . .venv/bin/activate
          mypy app
      - name: Run tests (pytest)
        run: |
          . .venv/bin/activate
          pytest
